spring:
  application:
    name: order

server:
  servlet:
    context-path: /aust

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  #  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 'aust1234'

app:
  order:
    history:
      status: ${HISTORY_STATUS}
      daysAgo: ${HISTORY_DAYSAGO}